### ISSUE TITLE
Create a splash screen

### ISSUE THREAD

**Issue by vmjoseph** [vmjoseph/family-recipes#1]
### Goal:

Create a splash screen that will display while resources are loading upon first opening of the app.

#### Tasks:
Actual design will probably change later, but for now:

- [x] Create splash screen component
- [x] Embed it into component lifecycle 
- [ ] Test for all platforms:
     - [ ]  iOS
     - [ ]  Android
     - [x] Web
     
**Resources**
****
![splash screen image](https://raw.githubusercontent.com/vmjoseph/family-recipes/main/assets/splash_1.png)
[Auth0's Splash Screen Tutorial](https://auth0.com/blog/creating-a-splash-screen-for-your-react-apps/)
